Dia,Cielo,Temp,Humedad,Viento,Juego
1,Lluvia,Calor,Alta,No,No
2,Lluvia,Calor,Alta,Si,No
3,Nublado,Calor,Alta,No,Si 
4,Soleado,Templado,Alta,No,Si 
5,Soleado,Frio,Normal,No,Si 
6,Soleado,Frio,Normal,No,No
7,Nublado,Frio,Normal,Si,Si 
8,Lluvia,Templado,Alta,Si,No
9,Lluvia,Frio,Normal,No,Si 
10,Soleado,Templado,Normal,No,Si 
11,Lluvia,Templado,Normal,No,Si 
12,Nublado,Templado,Alta,Si,Si 
13,Nublado,Calor,Normal,No,Si 
14,Soleado,Templado,Alta,Si,No
